package hr.fer.zemris.java.custom.scripting.lexer;

/**
 * Represents one single token generated by {@link Lexer}. Token has associated
 * value and type to itself. Type is described by enumeration {@link TokenType}
 * 
 * @author Marin Jurjevic
 * @see Lexer
 */
public class Token {

	/**
	 * type of token
	 * @see TokenType
	 */
	private TokenType type;
	
	/**
	 * value of this token
	 */
	private Object value;

	/**
	 * Public constructor for a single token.
	 * 
	 * @param type
	 *            {@link TokenType} value
	 * @param value
	 *            value of this token
	 * 
	 */
	public Token(TokenType type, Object value) {
		this.type = type;
		this.value = value;
	}

	/**
	 * Returns token's value.
	 * 
	 * @return value of this token
	 */
	public Object getValue() {
		return value;
	}

	/**
	 * Returns token's type.
	 * 
	 * @return type of this token
	 */
	public TokenType getType() {
		return type;
	}
}
