package hr.fer.zemris.java.tecaj.hw5.lexer;

/**
 * Represents one single token generated by {@link Lexer}. Token has associated
 * String value and type to itself. Type is described by enumeration
 * {@link TokenType}
 * 
 * @author Marin Jurjevic
 * @see Lexer
 */
public class Token {

	private TokenType type;
	private String value;

	/**
	 * Public constructor for a single token.
	 * 
	 * @param type
	 *            {@link TokenType} value
	 * @param value
	 *            value of this token
	 * 
	 */
	public Token(TokenType type, String value) {
		this.type = type;
		this.value = value;
	}

	/**
	 * Returns token's value.
	 * 
	 * @return value of this token
	 */
	public String getValue() {
		return value;
	}

	/**
	 * Returns token's type.
	 * 
	 * @return type of this token
	 */
	public TokenType getType() {
		return type;
	}
}
