package hr.fer.zemris.java.custom.scripting.lexer;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;

/**
 * Demonstration program for testing Lexer used in SmartScriptParser. It
 * initialises one lexer with given document and prints out token type and value
 * for each token generated by lexer object.
 * 
 * @author Marin Jurjevic
 *
 */
public class LexerDemo {

	public static void main(String[] args) throws IOException {

		String docBody = new String(Files.readAllBytes(Paths.get(args[0])), StandardCharsets.UTF_8);

		Lexer lexer = new Lexer(docBody);

		while (lexer.nextToken().getType() != TokenType.EOF) {
			if (lexer.getToken().getType() != TokenType.TAG_END && lexer.getToken().getType() != TokenType.TAG_START)
				System.out.println(lexer.getToken().getType() + "\t" + lexer.getToken().getValue());

			if (lexer.getToken().getType() == TokenType.TAG_START) {
				lexer.setState(LexerState.TAG);
			}
			if (lexer.getToken().getType() == TokenType.TAG_END) {
				lexer.setState(LexerState.TEXT);
			}
		}
	}

}
